# Generated by Django 5.2 on 2026-01-24 11:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_add_default_uoms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='price',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='subline_description',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='subline_number',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='uom',
        ),
        migrations.CreateModel(
            name='POLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subline_number', models.CharField(max_length=50)),
                ('subline_description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subline_items', to='invoices.purchaseorder')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_line_items', to='invoices.uom')),
            ],
            options={
                'db_table': 'po_line_items',
                'ordering': ['subline_number', 'id'],
            },
        ),
    ]
