# Generated by Django 5.2 on 2026-01-24 14:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_remove_purchaseorder_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cgst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('9.00'), help_text='CGST Rate (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='place_of_supply',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='po_date',
            field=models.DateField(blank=True, help_text='PO Date', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='po_number',
            field=models.CharField(blank=True, help_text='PO Number from client', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reverse_charge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reverse_charge_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sgst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('9.00'), help_text='SGST Rate (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='state_code',
            field=models.CharField(blank=True, help_text='State Code (e.g., 24 for Gujarat)', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vendor_code',
            field=models.CharField(blank=True, help_text='Vendor Code assigned by client', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='sac_code',
            field=models.CharField(blank=True, help_text='Service Accounting Code (SAC)', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('pan', models.CharField(blank=True, max_length=10, null=True)),
                ('cin', models.CharField(blank=True, help_text='Company Identification Number', max_length=21, null=True)),
                ('address', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('invoice_prefix', models.CharField(default='INV-', max_length=20)),
                ('default_due_days', models.IntegerField(default=30)),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5)),
                ('currency', models.CharField(default='₹ INR', max_length=10)),
                ('bank_name', models.CharField(blank=True, max_length=200, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('branch', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default company for new invoices')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoices.company'),
        ),
    ]
