# Generated by Django 5.2 on 2026-01-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_invoice_cgst_amount_invoice_cgst_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='stamp',
            field=models.ImageField(blank=True, help_text='Company stamp/logo for invoices', null=True, upload_to='company_stamps/'),
        ),
    ]
