# Generated by Django 5.2 on 2026-01-24 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_company_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='po_line_item',
            field=models.ForeignKey(blank=True, help_text='Linked PO Line Item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='invoices.polineitem'),
        ),
    ]
