# Generated by Django 5.2 on 2026-01-24 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_invoiceitem_po_line_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='invoices.company'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorder',
            unique_together={('company', 'po_number')},
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['company', 'po_number'], name='purchase_or_company_492c21_idx'),
        ),
    ]
