# Generated by Django 5.2 on 2026-01-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_purchaseorder_company_alter_purchaseorder_po_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bill_summary',
            field=models.FileField(blank=True, help_text='Bill Summary PDF', null=True, upload_to='invoices/bill_summaries/'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='measurement_sheet',
            field=models.FileField(blank=True, help_text='Measurement Sheet PDF', null=True, upload_to='invoices/measurement_sheets/'),
        ),
    ]
