# Generated by Django 5.2 on 2026-01-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_invoice_bill_summary_invoice_measurement_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the last reminder email was sent', null=True),
        ),
    ]
