# Generated by Django 5.2 on 2026-01-24 17:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_invoice_reminder_sent_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount received', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tds_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='TDS Deducted', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tds_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='TDS %', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('fine_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fine/Penalty', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('adjustment_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Other Adjustments (+/-)', max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Net amount after adjustments', max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('BANK_TRANSFER', 'Bank Transfer'), ('UPI', 'UPI'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('NEFT', 'NEFT'), ('RTGS', 'RTGS'), ('OTHER', 'Other')], default='BANK_TRANSFER', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Cheque/Transaction/Reference Number', max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=200, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('ON_HOLD', 'On Hold'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], default='RECEIVED', max_length=20)),
                ('is_on_hold', models.BooleanField(default=False, help_text='Payment on hold')),
                ('hold_reason', models.TextField(blank=True, help_text='Reason for hold', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoices.invoice')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
