# Generated by Django 5.2 on 2026-01-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='gstin',
            field=models.CharField(blank=True, help_text='GSTIN (15 characters)', max_length=15, null=True),
        ),
    ]
