# Generated by Django 5.2.12 on 2026-03-22 16:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_client_gstin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='udhyam_number',
            field=models.CharField(blank=True, help_text='Udhyam Registration Number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bill_to_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bill_to_gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bill_to_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='igst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('18.00'), help_text='IGST Rate (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_igst',
            field=models.BooleanField(default=False, help_text='Apply IGST instead of CGST/SGST'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ship_to_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ship_to_gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ship_to_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='polineitem',
            name='hsn_sac_code',
            field=models.CharField(blank=True, help_text='HSN/SAC Code', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_note_number', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('bill_to_name', models.CharField(blank=True, max_length=200, null=True)),
                ('bill_to_address', models.TextField(blank=True, null=True)),
                ('bill_to_gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('ship_to_name', models.CharField(blank=True, max_length=200, null=True)),
                ('ship_to_address', models.TextField(blank=True, null=True)),
                ('ship_to_gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_igst', models.BooleanField(default=False)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=Decimal('9.00'), max_digits=5)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=Decimal('9.00'), max_digits=5)),
                ('igst_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='invoices.client')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='invoices.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='invoices.invoice')),
                ('po_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='invoices.purchaseorder')),
            ],
            options={
                'db_table': 'credit_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('sac_code', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.creditnote')),
            ],
            options={
                'db_table': 'credit_note_items',
                'ordering': ['id'],
            },
        ),
    ]
