# Generated by Django 5.2 on 2026-03-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_company_udhyam_number_invoice_bill_to_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnoteitem',
            name='material_code',
            field=models.CharField(blank=True, help_text='Material/Service Code', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='material_code',
            field=models.CharField(blank=True, help_text='Material/Service Code', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='polineitem',
            name='material_code',
            field=models.CharField(blank=True, help_text='Material/Service Code', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='sac_code',
            field=models.CharField(blank=True, help_text='HSN/SAC Code', max_length=50, null=True),
        ),
    ]
