# Generated by Django 5.2 on 2026-03-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_creditnoteitem_material_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='state_code',
            field=models.CharField(blank=True, help_text='e.g. 24-Gujarat', max_length=100, null=True),
        ),
    ]
