# Generated by Django 5.2 on 2026-03-23 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_company_state_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnoteitem',
            name='po_line_item',
            field=models.ForeignKey(blank=True, help_text='Linked PO Line Item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_note_items', to='invoices.polineitem'),
        ),
    ]
